### ISSUE TITLE
Red transaction marker

### ISSUE THREAD

**Issue by julrichkieffer** [bpmn-io/camunda-transaction-boundaries#13]
__Describe the Bug__

The [transaction marker illustrated is a red bar](https://github.com/bpmn-io/camunda-transaction-boundaries/blob/master/docs/screenshot.png). However, after installing the plugin, a white "T" marker appears instead. The red marker is preferred as it's visually unobtrusive / more subtle.

__Steps to Reproduce__

1. Install this plugin
2. Place a user task or a service task (with Async Before checked)
3. Toggle this plugin to "on" state

__Actual Behavior__

Transaction boundaries are marked with a "T" in a white box with grey borders.

__Expected Behavior__

Transaction boundaries are marked with a red bar only.

__Environment__

- Host Camunda Modeller 4.12.0
- OS: Windows 10
- Plugin version: 0.4.2
- Library version: 1.1.2

**Comment by pinussilvestrus** [comment]
[The plugin](https://github.com/camunda/camunda-modeler-plugins/tree/master/camunda-transaction-boundaries-plugin) is using [different styles](https://github.com/camunda/camunda-modeler-plugins/blob/master/camunda-transaction-boundaries-plugin/style/style.css) as the underlying bpmn-js extension (this project). This is intended.

I think the rationale here is to keep the extension rather basic and let the integrator (the plugin) decide how to display it. 

I'll close this issue as `wont-fix` since it's expected. If you still think something should be changed or you have further information, feel free to re-open 👍
